version: '3'

services:
  api:
    image: 344108883756.dkr.ecr.eu-central-1.amazonaws.com/circles-api-ecr:latest
    env_file:
      - .env
    ports:
      - 0.0.0.0:8080:8080

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: -m 'enable depend figure right kit daughter job giraffe news window tonight more'
    ports: 
      - 8545:8545